/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type Product = {
    product: ({
        id: string;
        name: string;
        description: string;
        reviews: ({
            id: string;
            commentBody: string;
        })[];
    }) | null;
};
export type ProductVariables = {
    id: string;
};
